-- SQLite

CREATE TABLE IF NOT EXISTS utilisateurLogin (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nom TEXT NOT NULL,
    prenom TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    created_ad TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    admin BOOLEAN
);


CREATE TABLE IF NOT EXISTS contact (
    numMes INTEGER PRIMARY KEY AUTOINCREMENT,
    nomC TEXT NOT NULL,
    courriel TEXT NOT NULL,
    messages TEXT NOT NULL,
    sent_ad TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);


CREATE TABLE IF NOT EXISTS 18 (
    numB INTEGER PRIMARY KEY AUTOINCREMENT,
    nomA TEXT NOT NULL,
    coontenue TEXT NOT NULL,
    made_ad TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);


CREATE TABLE IF NOT EXISTS 19 (
    numB INTEGER PRIMARY KEY AUTOINCREMENT,
    nomA TEXT NOT NULL,
    coontenue TEXT NOT NULL,
    made_ad TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);


CREATE TABLE IF NOT EXISTS 20 (
    numB INTEGER PRIMARY KEY AUTOINCREMENT,
    nomA TEXT NOT NULL,
    coontenue TEXT NOT NULL,
    made_ad TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);


CREATE TABLE IF NOT EXISTS 21 (
    numB INTEGER PRIMARY KEY AUTOINCREMENT,
    nomA TEXT NOT NULL,
    coontenue TEXT NOT NULL,
    made_ad TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);



